#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

echo "Hello World!" | sudo tee /var/www/html/index.html
string_="server_name _;\n\trewrite ^\/redirect_me https\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_/" /etc/nginx/sites-enabled/default

sudo service nginx restart
